# Generated by Django 5.0.4 on 2024-05-04 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vaccine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Pet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("submitter", models.CharField(max_length=100)),
                ("species", models.CharField(max_length=30)),
                ("breed", models.CharField(blank=True, max_length=30)),
                ("description", models.TextField()),
                (
                    "sex",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Male"), ("F", "Female")],
                        max_length=1,
                    ),
                ),
                ("subission_date", models.DateTimeField()),
                ("age", models.IntegerField()),
                (
                    "vaccinations",
                    models.ManyToManyField(blank=True, to="adoptions.vaccine"),
                ),
            ],
        ),
    ]
